### ISSUE TITLE
https://duh.run website broken

### ISSUE THREAD

**Issue by mithro** [sifive/duh#65]
Just shows "test" see below;
![image](https://user-images.githubusercontent.com/21212/73949093-37001e80-48fa-11ea-9134-69ca116ed779.png)

**Comment by drom** [comment]
Agree that we need to create a good landing page with:
* Home / About
* Download / Install
* Docs / Examples
* News / Release Notes

**Comment by drom** [comment]
@mithro Is it better now?
![image](https://user-images.githubusercontent.com/511872/77197865-27502a00-6aa3-11ea-9b19-4257260e3b9b.png)

**Comment by mithro** [comment]
LGTM!
